pipeline {
    agent any 
    parameters {
        string(name: 'PERSON', defaultValue: 'Ms Sarah Furtado', description: 'Who should I say hello to?')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    }
    stages {
        stage('Static Analysis') {
            steps {
                echo 'Hii Devops practical is on 26th Oct' 
            }
        }
        stage('Compile') {
            steps {
                echo 'U are doing good' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'All the best' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'DevOps practical exam is on ' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'pipe4' 
            }
        }
        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"
                echo "Choice: ${params.CHOICE}"
            }
        }
        stage('One') {
            input {
                message "Hii,should we continue?"
                ok "Yes, we should."
                submitter "sarah,furtado"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Ms Sarah', description: 'How are you?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, I'm fine ,nice to meet you."
            }
        stage('Publish Artifacts') {
            steps {
                echo 'Save the assemblies generated from the compilation' 
            }
        }
    }
}
